## Create a boolean array

In [ ]:
import numpy as np
a1 = np.array([1, 0, 1], dtype='bool')
print(a1)

[ True False  True]

## Create an object array to hold numbers as well as strings

In [ ]:
a2 = np.array([1, 'a'], dtype='object')
print(a2)
print(type(a2))

[1 'a']
<class 'numpy.ndarray'>

## Convert an array back to a list

In [ ]:
a2 = np.array([1, 'a'], dtype='object')
a3=a2.tolist()
print(a3)
print(type(a3))

[1, 'a']
<class 'list'>

## Represent missing values

In [ ]:
a4 = np.array([[1, 'sas', 3],
               [4, 5, 6]])
print(a4)
print('\n')

a4[0,1] = np.nan  # not a number
print(a4)

[['1' 'sas' '3']
 ['4' '5' '6']]


[['1' 'nan' '3']
 ['4' '5' '6']]

## Compute mean, min, max on the ndarray

In [ ]:
a5 = np.random.randint(10, size=(4, 5))
print(a5)
print('\n')
print("Mean value is: ", a5.mean())
print("Max value is: ", a5.max())
print("Min value is: ", a5.min())

[[5 1 0 1 0]
 [0 6 3 5 9]
 [9 5 7 6 1]
 [4 3 4 0 8]]


Mean value is:  3.85
Max value is:  9
Min value is:  0

## Compute the minimum values row wise or column wise

In [ ]:
a6 = np.random.randint(10, size=(4, 5))
print(a6)
print('\n')
print("Column wise minimum: ", np.amin(a6, axis=0))
print("Row wise minimum: ", np.amin(a6, axis=1))

[[5 2 6 0 2]
 [7 6 1 4 7]
 [5 5 1 7 6]
 [7 5 1 1 7]]


Column wise minimum:  [5 2 1 0 2]
Row wise minimum:  [0 1 1 1]

## Compute cumulative sum

In [ ]:
a7 = np.random.randint(10, size=(4, 5))
print(a7)
print('\n')
print(np.cumsum(a7))

[[9 7 3 1 6]
 [0 8 7 6 0]
 [6 1 5 4 6]
 [7 7 2 6 0]]


[ 9 16 19 20 26 26 34 41 47 47 53 54 59 63 69 76 83 85 91 91]

## Obtain the common items between two numpy arrays

In [ ]:
a8 = np.array([1,2,3,2,3,4,3,4,5,6])
a9 = np.array([7,2,10,2,7,4,9,4,9,8])

a10=np.intersect1d(a8,a9)
print(a10)

[2 4]

## Remove items from one numpy array that exist in another

In [ ]:
a11 = np.array([1,2,3,4,5])
a12 = np.array([5,6,7,8,9])

a13 = np.setdiff1d(a11,a12)
print(a13)

[1 2 3 4]

## Obtain the positions where elements of two numpy arrays match

In [ ]:
a14 = np.array([1,2,3,2,3,4,3,4,5,6])
a15 = np.array([7,2,10,2,7,4,9,4,9,8])

a16=np.where(a14 == a15)
print(a16)

(array([1, 3, 5, 7]),)

## Q1: Extract all numbers between between 5 and 15 from x

- **Input** x = np.array([2, 6, 1, 9, 10, 3, 27])
- **Expected Output** [ 6  9 10]

In [ ]:

x = np.array([2, 6, 1, 9, 10, 3, 27])
y = np.where((x >= 5) & (x <= 15))
z=x[y]
print(z)

[ 6  9 10]